### ISSUE TITLE
Questions about forking

### ISSUE THREAD

**Issue by ChrysanthCow** [haykam821/Caricodec#2]
Because this is MIT license, I assume that this is safe to fork and/or use code from this provided I follow the license and include a disclaimer showing your MIT license where your code is used?

I kinda wanted to make my own codec based config for a general library mod but a friend linked me this and i felt it was a better implementation than I could do, so hopefully you'd be fine with such a fork existing?

Amazing work on this btw.

**Comment by haykam821** [comment]
Forking is fine as long as you follow the license terms.
